// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xouacgqlqkttvwaqcvdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdWFjZ3FscWt0dHZ3YXFjdmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTM2MjUsImV4cCI6MjA3NDQyOTYyNX0.OSCrcvaR9LZcrOoAye-n7p6v3oiTXCcllpNStlYxh-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});